name: "Infrastructure as a code workflow"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      resource_name:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      terragrunt_version:
        required: true
        type: string

jobs:
  iac:
    name: Cloud Infrastructure Creation
    environment: 
      name: ${{ inputs.environment }}
    env:
      # variables
      AWS_DEFAULT_REGION: ${{ vars.aws_region }}
      DYNAMODB_TABLE: ${{ vars.dynamodb_table}}
      BUCKET_REGION: ${{ vars.bucket_region }}
      BUCKET_NAME: ${{ vars.bucket_name }}
      # inputs
      NAME: ${{ inputs.resource_name }}
      ENV: ${{ inputs.environment }}
      # secrets
      GHFLOW_SECRET: ${{ vars.gh-flow_secret }}
      
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}
    steps:
    - name: Git checkout 
      uses: actions/checkout@v4

    - name: Configure AWS 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.aws_role }}
        aws-region: ${{ vars.aws_region }}
        role-session-name: Github-OIDC

    - name: Setup Terragrunt ${{ inputs.terragrunt_version }}
      run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt_version }}/terragrunt_linux_amd64
          mv terragrunt_linux_amd64 terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/
          terragrunt -v

      # Usually for deployment from Terraform    
    - name: Install Helm 
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        
    - name: Terragrunt Init 
      id: init    
      run: terragrunt run-all init -terragrunt-non-interactive

    - name: Terragrunt plan 
      id: plan  
      run: terragrunt run-all plan -terragrunt-non-interactive

    - name: Terragrunt apply 
      id: apply  
      run: terragrunt run-all apply -terragrunt-non-interactive